version: '3.8'

services:
  web:
    build:
      context: $(CONTEXTO)
      dockerfile: examen/dockerfiles/js/react/Dockerfile
    container_name: ${CONTAINER_NAME}
    ports:
      - "${NGINX_PORT}:80"    # Mapeo del puerto de Nginx
      - "${SSH_PORT}:22"      # Mapeo del puerto SSH
    volumes:
      - ../prueba/html:/var/www/html  # Opcional, para personalizar el contenido de Nginx
    # environment:
    #   - ENVIRONMENT=production
    restart: always

